Ewlj 80 basic page prototype
palantirnet/ama-style-guide-joe pull request #7
Opened 2018-01-19 19:18 UTC by aCyborg

## Ticket(s)

**Github Issue**

N/A

**Jira Ticket**

- [EWLj-80: Basic Page Prototype](https://issues.ama-assn.org/browse/EWLJ-80)

## Description

Create a podcast detail page. This includes:
* Page hero atom
* Page header molecule
* Rail nav Molecule
* Two-column-left--simple layout

## To Test

- [ ] Spin up Patternlab
- [ ] Review the Page hero atom
- [ ] Review the header molecule
- [ ] Review the Rail nav Molecule
- [ ] Review Two-column-left--simple layout
- [ ] Review the Basic Page Page

## Visual Regressions
N/A

## Relevant Screenshots/GIFs
N/A

## Remaining Tasks
N/A

## Additional Notes
N/A

2018-01-19 20:30 UTC, gleroux02 commented
@aCyborg seeing problems with our favorite component the share links:
![image](https://user-images.githubusercontent.com/394763/35170286-4a78a0c2-fd25-11e7-9e7c-b11ca743cdd9.png)

2018-01-19 20:40 UTC, gleroux02 requested changes
Just the share issue and childs :)

2018-01-19 20:40 UTC, gleroux02 commented on styleguide/source/_patterns/02-molecules/rail-nav.md
> +  childs:
children?

2018-01-22 15:38 UTC, aCyborg commented
@gleroux02 I've updated the childs to be children, but I'm going to leave the social icons as they are for now since I completely re-thought social sharing in my next PR. Once this gets merged in, we can take a closer look at this social setup in that PR.

2018-01-23 21:25 UTC, gleroux02 approved these changes
👍  sounds good about the share links.

2018-01-23 21:25 UTC, merged